#!/usr/bin/env bash
# IBM SDK for Node.js Buildpack
# Copyright 2014 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Sets the NODE_EXECUTABLE environment variable and restarts the app.
#
# Usage:
# run PORT [break|no-break]
#
# If the 2nd argument is omitted, no-break is assumed.
#
app_management_dir=$(cd `dirname $0`/../.. && pwd)
cd $app_management_dir

APP_PORT=$1
BREAK="${2:-no-break}" # This form sets BREAK to "no-break" if $2 is empty

if [ -z "${APP_PORT}" ]; then
  APP_PORT=$(( $PORT + 1 ))
  echo "Port arg was not provided. Starting app on PORT+1: $APP_PORT"
fi

scripts/stop
scripts/start ${APP_PORT} $BREAK
