#!/usr/bin/env bash
# IBM SDK for Node.js Buildpack
# Copyright 2014 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

app_management_dir=$(cd `dirname $0`/../.. && pwd)
cd $app_management_dir

pid=$(cat ${app_management_dir}/handlers/start-inspector/inspector.pid)
kill -9 ${pid}

# Reset the executable
export NODE_EXECUTABLE=node

for key in inspector procotol; do
    ${app_management_dir}/scripts/remove_proxy_entry "$key"
done
