#!/usr/bin/env ruby
# Encoding: utf-8
# IBM SDK for Node.js Buildpack
# Copyright 2015 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

require 'fileutils'
app_dir = File.expand_path('../../..', File.dirname(__FILE__)).freeze

# Copy enhanced bootscript to application if RMU is enabled
bootscript = ENV['BOOT_SCRIPT']
bootfile = File.basename("#{bootscript}")
if (File.exists?("#{app_dir}/vendor/#{bootfile}.enhanced") && File.exists?("#{app_dir}/#{bootscript}"))
  # Create backup of boot script
  boot_orig = File.new("#{app_dir}/#{bootscript}.orig", "w+")
  FileUtils.copy_file("#{app_dir}/#{bootscript}", boot_orig, "w+")
  
  # Remove original boot script and replace it with the enhanced script
  FileUtils.remove_file("#{app_dir}/#{bootscript}")
  FileUtils.copy_file("#{app_dir}/vendor/#{bootfile}.enhanced", "#{app_dir}/#{bootscript}", "w+")
end
