#!/usr/bin/env bash

# Exit code:
# 0 if inspector is started.
# 1 if stopped.
#
pidfile=$(dirname "$0")/../start-inspector/inspector.pid

if ps -p "$(cat $pidfile 2>/dev/null)" &>/dev/null ; then
    exit 0
else
    exit 1
fi
