#!/usr/bin/env bash

# Exit code:
# 0 if HC is started.
# 1 if HC stopped.
#
pidfile=$(dirname "$0")/../start-hc/healthcenter.pid

if ps -p "$(cat $pidfile 2>/dev/null)" &>/dev/null ; then
    exit 0
else
    exit 1
fi
