#!/usr/bin/env bash
# Encoding: utf-8
# IBM SDK for Node.js Buildpack
# Copyright 2014-2015 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# Prints, to standard output, the `node` command to be used for starting
# the app runtime. The node command changes based on whether suspend (break)
# is desired, and whether Node Inspector is running.

# Usage:
#  get-node-executable break
#  get-node-executable no-break
#
# Exit codes:
# 0    : success
# other: an error occurred

app_management_dir=$(cd `dirname $0`/../ && pwd)
bp_dir=$(cd `dirname $0`/../.. && pwd)
cd $app_management_dir

source $app_management_dir/utils/node_utils.sh
source $app_management_dir/utils/handler_utils.sh

BREAK=$1

case "$BREAK" in
    'break' | 'no-break')
        ;;
    *)
        echo "Usage: $0 break or $0 no-break" >&2
        exit 1
        ;;
esac

enabled=($(enabled_handlers))

if [[ " ${enabled[*]} " == *" hc "* ]]; then
  node_cmd="node-hc"
else
  node_cmd="node"
fi

if [[ " ${enabled[*]} " == *" inspector "* ]]; then
    if inspector_builtin $bp_dir/vendor/node; then
        DEBUG_PORT=$(handler_port 'inspector' 'debugport' 9229)
        if [ "$BREAK" == "break" ]; then
            echo "${node_cmd} --inspect=${DEBUG_PORT} --debug-brk"
        else
            echo "${node_cmd} --inspect=${DEBUG_PORT}"
        fi
    else
        DEBUG_PORT=$(handler_port 'inspector' 'debugport' 5858)
        if [ "$BREAK" == "break" ]; then
            echo "${node_cmd} --debug-brk=${DEBUG_PORT}"
        else
            echo "${node_cmd} --debug=${DEBUG_PORT}"
        fi
     fi
 else
     if [ "$BREAK" == "break" ]; then
        echo "Node Inspector is not running; cannot suspend." >&2
        exit 2
    else
        echo "${node_cmd}"
    fi
fi
