#!/usr/bin/env bash
# Usage: install                 Install if necessary.
handler_dir=$(cd `dirname $0` && pwd)/../start-shell
install_helper=${handler_dir}/../../utils/install_helper

${install_helper} "--dir=${handler_dir}" "--label=shell" "$1"
