#!/usr/bin/env ruby
# Encoding: utf-8

require 'json'

# The user must pass in two String parameters. The first is the key used to insert the entry into the "entries" hash.
# The second is a JSON String that is parsed to obtain the value to insert (normally a hash).
raise 'Please pass me a key' if ARGV[0].nil?
key = ARGV[0]
raise 'Please pass me a value' if ARGV[1].nil?
value = JSON.parse(ARGV[1])

# Calculate the app dir location. Do not rely on the current working directory being the app dir.
app_dir = File.expand_path('../..', File.dirname(__FILE__))

proxy_config_file = File.join(app_dir, '.app-management', 'bin', 'proxy.config')
data = if File.exist?(proxy_config_file)
         JSON.parse(File.open(proxy_config_file, 'r:utf-8', &:read))
       else
         {}
       end
entries = data['entries']
if entries.nil?
  entries = {}
  data['entries'] = entries
end

# Add entry into Hash and write back to disk. Overwrite existing entry
entries[key] = value
File.open(proxy_config_file, 'w:utf-8') do |file|
  file.write(data.to_json)
  file.flush
end
