#!/usr/bin/env bash
# Encoding: utf-8
# IBM SDK for Node.js Buildpack
# Copyright 2014 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Checks the state of the Node.js runtime. This is a simple test
# that determines if the process having PID given by $HOME/runtime.pid
# is running.
#
# Exit codes:
# 0: runtime is started
# 1: runtime is stopped
# 2: an error occurred
pidfile=$HOME/runtime.pid
started=0
stopped=1
error=2

# Check pidfile
if [ ! -f "$pidfile" ]; then
    exit $stopped
fi

pid=$(cat ${pidfile} 2> /dev/null)
if [ -z "$pid" ]; then
    echo "Invalid pid: $pid" >&2
    exit $error
fi

# Check if process having that PID is running.
ps -p $pid > /dev/null
running=$?
if [ "$running" -eq 0 ]; then
    exit $started
elif [ "$running" -eq 1 ]; then
    exit $stopped
fi

exit $error
